void reset_to_98(int *n);
void swap_int(int *a, int *b);
void _puts(char *str);
int _strlen(char *s);
void print_rev(char *s);
void rev_string(char *s);
void puts2(char *str);
void puts_half(char *str);
int _putchar(char c);
char *_strcat(char *dest, char *src);
char *_strncat(char *dest, char *src, int n);
